[package]
name = "Tcard"
version = "0.0.0"

[addresses]
NamedAddr = "0xDEADBEEF"

[dependencies]
MoveStdlib = { local = "/Users/Zi/Desktop/Grad1.0/ECE1770/move/diem/diem-move/diem-framework/move-stdlib/", addr_subst = { "Std" = "0x1" } }